config_campaignservice              = "https://campaign-qa-int.trialcard.com/api/v5/"
config_documentservice              = "https://document-qa-int.trialcard.com/api/v3/"
config_eservicesorchestratorservice = "https://eservicesorchestrator-qa-int.trialcard.com/api/v1/"
defaultprogramid                    = "102494"
fallbackprogramids_0                = "40088"
obfuscateduserid                    = "NpHJCU3HogS5Ow4TdVOI1Q~~"
keyvault_secret                     = "sfintegration-test"
keyvault_url                        = "https://kv-salesforce-dev-01.vault.azure.net/"
appinsights_instrumentationkey      = "dcc052da-f7bc-46ad-82df-09eb7a3a8a08"
appinsights_connectionstring        = "InstrumentationKey=dcc052da-f7bc-46ad-82df-09eb7a3a8a08;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/"
backend_eservicesorchestrator       = "https://eservicesorchestrator-qa-int.trialcard.com/api/v1"
backend_apigateway                  = "https://apigateway-qa.trialcard.com"
auth0DefaultClientId                = "cqT24g198ceniHosCn3xoQQWGjQkMroX"
auth0DefaultClientSecret            = "igj1ajvI1x57O1It7tCF8gQFBbz_l8zwJXAn5sY2nfpphFQsbKD_UYMCyJlQ04cv"
auth0AuthorizationServer            = "https://trialcard-api-test.us.auth0.com/oauth/token"
eservicesOrchestratorAudience       = " "
eservicesOrchestratorProgramid      = "B9FE39BA-E418-4456-AB43-011AE530EC77"
service_account                     = "sfintegrationapi_qa"
