trigger:
  branches:
    include:
    - main
  paths:
    include:
    - "infrastructure/azure_container_registry/*"

resources:
  repositories:
  - repository: TerraformTemplates
    name: Infrastructure/TerraformTemplates
    type: git
    ref: main
  - repository: pipelinekit
    name: DevOps/Pipelinekit
    type: git
    ref: main
  - repository: TerraformConfigurations
    name: Infrastructure/TerraformConfigurations
    type: git
    

variables:
- template: variablegroups/terraform/build/vg_terraform_build_global.yml@pipelinekit
- name: root_modulepath
  value: "$(Build.SourcesDirectory)/TerraformConfigurations/$(project_name)/azure_container_registry/$(root_module)/module"

stages:
- stage: "build"
  displayName: "Build Terraform Templates"
  variables:
  - name: tf_templates
    value: "acr_template/v1, iam_template/v1"
  - name: root_module
    value: "enterprise_services"
  - name: root_module_path
    value: "$(Build.SourcesDirectory)/TerraformConfigurations/infrastructure/azure_container_registry/$(root_module)/root_module"
  jobs:
  - template: jobs/terraform/build/job_terraform_build.yml@pipelinekit
