trigger:
  branches:
    include:
    - main
  paths:
    include:
    - "azure_virtual_desktop/deployment_modules/root_module_example.tf"

resources:
  repositories:
  - repository: TerraformTemplates
    name: Infrastructure/TerraformTemplates
    type: git
    ref: main
  - repository: pipelinekit
    name: DevOps/Pipelinekit
    type: git
    ref: ma-initialsetup
  - repository: TerraformConfigurations
    name: Infrastructure/TerraformConfigurations
    type: git
    ref: ma-moduledeploymentexample

variables:
- template: variablegroups/terraform/build/vg_terraform_build_global.yml@pipelinekit
- name: root_modulepath # Default path to the root module
  value: "$(Build.SourcesDirectory)/TerraformConfigurations/$(project_name)/$(root_module)/module"

stages:
- template: stages/terraform/stage_terraform_build.yml@pipelinekit
  parameters: # Parameters for the stage template
    root_module: root_module_example
    project_name: azure_virtual_desktop
    variables: root_module_example_build.yml
