apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: <<provider_class>>
  namespace: <<namespace>>
spec:
  provider: azure
  secretObjects:
  - secretName: <<cert_name>>
    type: kubernetes.io/tls
    data:
    - objectName: <<cert_name>>
      key: tls.key
    - objectName: <<cert_name>>
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <<kv_provider_id>>
    keyvaultName: <<keyvault_name>>
    objects: |
      array:
        - |
          objectName: <<cert_name>>
          objectType: secret
    tenantId: <<azure_tenant_id>>
